// 1. Escribe un comentario en una línea
    //Aprendiendo Js

// 2. Escribe un comentario en varias líneas
    /*Aprendiendo Js
        Y practicando*/

// 3. Declara variables con valores asociados a todos los datos de tipo primitivos
    let Nombre = ("Rodney");
    let Edad = (18);
    let esEstudiante = true;
    let Simbolo = Symbol("Este es un simbolo");
    let Indefinido;
    let bigInt = 6767676767676767676767676767676767676767676767676767676767676767n

// 4. Imprime por consola el valor de todas las variables
console.log("Varibales actualizadas");
    console.log(Nombre);
    console.log(Edad);
    console.log(esEstudiante);
    console.log(Simbolo);
    console.log (Indefinido);
    console.log(bigInt);
// 5. Imprime por consola el tipo de todas las variables
    console.log();
console.log("Tipos de variables");
    console.log(typeof Nombre);
    console.log(typeof Edad);
    console.log(typeof esEstudiante);
    console.log(typeof Simbolo);
    console.log(typeof  Indefinido);
    console.log(typeof bigInt);

// 6. A continuación, modifica los valores de las variables por otros del mismo tipo
    Nombre = ("Camilo");
    Edad = (19);
    esEstudiante = false;
    Simbolo = Symbol("Este es otro simbolo");
    Indefinido = "España";
    bigInt = 100000000000000000000000000000000000000000000000000000000000000000000n

// 7. A continuación, modifica los valores de las variables por otros de distinto tipo
    Nombre = 20;
    Edad = ("Ginela");
    Simbolo = true;
    esEstudiante = Symbol("Ultimo simbolo");
    Indefinido = 9999999999999990999999999999999999999999999999999999999999999999999n
    bigInt = ("Perez");

// Varibales actualizadas
    console.log();
console.log("Varibales actualizadas");
    console.log(Nombre);
    console.log(Edad);
    console.log(esEstudiante);
    console.log(Simbolo);
    console.log (Indefinido);
    console.log(bigInt);
// 8. Declara constantes con valores asociados a todos los tipos de datos primitivos

/*
    const Nombre = ("Daniel");
    const Edad = (50);
    const esEstudiante = false;
    const Simbolo = Symbol("Este es un simbolo constante");
    const Indefinido;
    const bigInt = 666666666666666666666666666666666666666666666666666666666666666666666n
*/

// 9. A continuación, modifica los valores de las constantes

    /*
        Nombre = ("constModificado");
        Edad = 90;
        esEstudiante = true;
        Simbolo = Symbol("Simbolo constante cambiado");
        Indefinido;
        bigInt = (1333333333333333333333333333333333333333333333333333333);
    */

// 10. Comenta las líneas que produzcan algún tipo de error al ejecutarse
    //Respuesta = 9