/*alert("Ejercicio #1")

let dia = (prompt("Ingresa un dia"))

let mes = prompt("Ingresa un mes")

let año = prompt("Ingrsa un año")


if (dia == 25 && mes == "Diciembre") {
    document.write("Dia = " + dia + "<br>")
    document.write("Mes = " + mes + "<br>")
    document.write("Año = " + año + "<br>")
    document.write("!!Es navidad!! <br>")
    document.write("<br>")
} else if (dia == 25 && mes == "diciembre") {
    document.write("Dia = " + dia + "<br>")
    document.write("Mes = " + mes + "<br>")
    document.write("Año = " + año + "<br>")
    document.write("!!Es navidad!! <br>")
} else {
    document.write("Dia = " + dia + "<br>")
    document.write("Mes = " + mes + "<br>")
    document.write("Año = " + año + "<br>")
    document.write("No es navidad")
}

alert("Ejercicio Terminado")
*/
