/*alert("Ejercicio #4")
let sueldo = parseFloat(prompt("Digite su sueldo"))
let antiguedad = parseInt(prompt("Ingrese su antiguedad en la empresa"))

if (sueldo < 500 && antiguedad >= 10) {
    let sueldoTotal = sueldo + sueldo * 0.20
    document.write("Se aumenta el sueldo <br>")
    document.write("Sueldo total = " + sueldoTotal)
}

if (sueldo < 500 && antiguedad < 10) {
    let sueldoTotal = sueldo + sueldo * 0.05
    document.write("Se aumenta el sueldo <br>")
    document.write("Sueldo total = " + sueldoTotal)
} else {
    document.write("No se aumenta el sueldo <br>")
    document.write("Sueldo total = " + sueldo)
}

alert("Ejercicio terminado")

*/