/*
alert("Ejercicio #3")

let n1 = parseInt(prompt("Ingresa el primer numero"))
let n2 = parseInt(prompt("Ingresa el primer numero"))
let n3 = parseInt(prompt("Ingresa el primer numero"))

if(n1 < 10 && n2 < 10 && n3 < 10){
    document.write("Todos los numeros ingresados son menor a 10")
}

else if(n1 > 10 && n2 < 10 && n3 < 10){
    document.write("Solo el primer numero es mayor a 10")
}

else if(n1 < 10 && n2 > 10 && n3 < 10){
    document.write("Solo el segundo numero es mayor a 10")
}

else if(n1 < 10 && n2 < 10 && n3 > 10){
    document.write("Solo el tercer numero es mayor")
}

alert("Ejercicio terminado")
*/
