/*
alert("Ejercicio #2")

let num1 = (parseInt(prompt("Ingresa un numero")))

let num2 = (parseInt(prompt("Ingresa otro numero")))

let num3 = (parseInt(prompt("Ingresa un ultimo numero")))

if(num1 == num2 && num1 == num3 && num2 == num3){
    let operacion = (num1 + num2) * num3
    document.write("Resultado = " + operacion)
}else{
    document.write("!!ERROR!!")
}

alert("Ejercicio terminado")
    */