/*
alert("Seleccione una de estas palabras a traducit (Casa, Perro, Mesa, Cat) <br>")
let opcion = prompt("Ingrese su palabra")

switch (opcion) {
    case "Casa":
        document.write("House")
        break;

    case "Perro":
        document.write("Dog")
        break;

    case "Mesa":
        document.write("Table")
        break;

    case "Gato":
        document.write("Cat")
        break;
}

alert("Ejercicio terminado")
*/