let num1 = parseInt(prompt("Ingresa el primer numero"))
let num2 = parseInt(prompt("Ingresa el segundo numero"))
let num3 = parseInt(prompt("Ingresa el tercero numero"))
let num4 = parseInt(prompt("Ingresa el cuarto numero"))

let suma = num1 + num2
let producto = num3 * num4

document.write("---Ejercicio 2---" + "<br>")
document.write("Suma de los dos primeros numeros = " + suma + "<br>")
document.write("Producto del tercer y cuarto numero = " + producto + "<br>")
document.write("<br>")
alert("Ejercicio finalizado")