let n1 = parseInt(prompt("Ingresa primer numero"))
let n2 = parseInt(prompt("Ingresa segundo numero"))
let n3 = parseInt(prompt("Ingresa tercer numero"))
let n4 = parseInt(prompt("Ingresa cuato numero"))

let sumatoria =  n1 + n2 + n3 + n4
let multi = n1 * n2 * n3 * n4

document.write("---Ejercicio 3---" + "<br>")
document.write("Sumatoria total = " + sumatoria + "<br>")
document.write("Producto total = " + multi + "<br>")
document.write("<br>")
alert("Ejercicio finalizado")

